# Generated by Django 4.2 on 2025-10-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEmotionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('detected_emotion', models.CharField(max_length=100)),
                ('intensity', models.FloatField()),
                ('segment_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_timeline', to='audio.audioentry')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
