# Generated by Django 4.2 on 2025-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audioemotiontimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioentry',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
