# Generated by Django 5.2.7 on 2025-10-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_url', models.FileField(upload_to='visual_entries/')),
                ('caption', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisualInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_objects', models.JSONField(default=list)),
                ('dominant_colors', models.JSONField(default=list)),
                ('emotion_detected', models.CharField(blank=True, max_length=50)),
                ('tags_generated', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visual_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='visual.visualentry')),
            ],
        ),
    ]
