# Generated by Django 5.2.7 on 2025-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textEntries', '0004_tag_entry_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentryinsight',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
