# Generated by Django 5.2.7 on 2025-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textEntries', '0005_textentryinsight_goals_alter_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentryinsight',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
