# Generated by Django 4.2 on 2025-10-12 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellbeingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('mood_score', models.IntegerField(help_text='Mood score from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.IntegerField(help_text='Energy level from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.FloatField(help_text='Hours of sleep', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('productivity_score', models.IntegerField(help_text='Productivity score from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wellbeing Record',
                'verbose_name_plural': 'Wellbeing Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoutineRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('morning', 'Morning Routine'), ('evening', 'Evening Routine'), ('exercise', 'Exercise'), ('meditation', 'Meditation'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep Hygiene'), ('productivity', 'Productivity Tip'), ('stress', 'Stress Management')], max_length=50)),
                ('description', models.TextField()),
                ('ai_generated', models.BooleanField(default=True)),
                ('efficiency_score', models.FloatField(help_text='Efficiency score from 0-1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wellbeing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='wellbeing.wellbeingrecord')),
            ],
            options={
                'verbose_name': 'Routine Recommendation',
                'verbose_name_plural': 'Routine Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
